language: node_js
node_js:
  - node

cache: npm

before_script:
  - npm install -g speccy
  - npm install -g redoc-cli

script:
  - speccy lint --skip openapi-tags-alphabetical swiss-ng-api.yaml
  - redoc-cli bundle swiss-ng-api.yaml
